import { csvEscape, safePathSegment } from "@voice-foundry/domain";

export type ExportAsset = {
  id: string;
  phraseId: string;
  text: string;
  synthesisText: string;
  group: string;
  category: string;
  src: string;
  mimeType: string;
  byteSize: number;
  durationMs: number | null;
  sha256: string;
  voiceProfileVersion: number;
  takeId: string;
  metadata: Record<string, unknown>;
};

export type ExportManifest = {
  schemaVersion: 1;
  generatedAt: string;
  projectId: string;
  voiceProfileVersionId: string;
  assets: ExportAsset[];
};

export type ExportValidation = {
  valid: boolean;
  errors: string[];
  warnings: string[];
  assetCount: number;
  totalBytes: number;
};

export function outputFileName(stableId: string, extension: string): string {
  const cleanExtension = extension.toLocaleLowerCase("en-US").replace(/[^a-z0-9]/g, "");
  if (!cleanExtension) throw new Error("Audio extension is invalid.");
  return `${safePathSegment(stableId)}.${cleanExtension}`;
}

export function sortExportAssets(assets: ExportAsset[]): ExportAsset[] {
  return [...assets].sort((left, right) => left.id.localeCompare(right.id, "en"));
}

export function validateExportAssets(assets: ExportAsset[]): ExportValidation {
  const errors: string[] = [];
  const warnings: string[] = [];
  const ids = new Set<string>();
  const paths = new Set<string>();
  const takes = new Set<string>();
  let totalBytes = 0;

  for (const asset of assets) {
    if (ids.has(asset.id)) errors.push(`Duplicate asset ID: ${asset.id}`);
    ids.add(asset.id);

    const normalizedPath = asset.src.replaceAll("\\", "/");
    if (
      normalizedPath.startsWith("/")
      || normalizedPath.split("/").some((segment) => segment === ".." || segment === ".")
    ) {
      errors.push(`Unsafe export path for ${asset.id}: ${asset.src}`);
    }
    if (paths.has(normalizedPath)) errors.push(`Path collision: ${normalizedPath}`);
    paths.add(normalizedPath);

    if (takes.has(asset.takeId)) warnings.push(`Take is referenced more than once: ${asset.takeId}`);
    takes.add(asset.takeId);

    if (!asset.mimeType.startsWith("audio/")) {
      errors.push(`Invalid audio MIME type for ${asset.id}: ${asset.mimeType}`);
    }
    if (!/^[a-f0-9]{64}$/i.test(asset.sha256)) {
      errors.push(`Invalid SHA-256 for ${asset.id}`);
    }
    if (!Number.isSafeInteger(asset.byteSize) || asset.byteSize < 0) {
      errors.push(`Invalid byte size for ${asset.id}`);
    } else {
      totalBytes += asset.byteSize;
    }
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings,
    assetCount: assets.length,
    totalBytes,
  };
}

export function buildChecksums(assets: ExportAsset[]): string {
  return `${sortExportAssets(assets)
    .map((asset) => `${asset.sha256}  ${asset.src}`)
    .join("\n")}\n`;
}

export function buildAudioMap(assets: ExportAsset[]): string {
  const entries = sortExportAssets(assets)
    .map((asset) => `  ${JSON.stringify(asset.id)}: ${JSON.stringify(`/${asset.src}`)},`)
    .join("\n");
  return [
    "// Generated by Frase Uno Voice Foundry. Do not edit by hand.",
    "export const FRASE_UNO_AUDIO = {",
    entries,
    "} as const;",
    "",
    "export type FraseUnoAudioId = keyof typeof FRASE_UNO_AUDIO;",
    "",
  ].join("\n");
}

export function buildPhrasesCsv(assets: ExportAsset[]): string {
  const header = [
    "id", "text", "synthesis_text", "group", "category", "src", "mime_type",
    "byte_size", "duration_ms", "sha256", "voice_profile_version", "take_id",
  ];
  const rows = sortExportAssets(assets).map((asset) => [
    asset.id,
    asset.text,
    asset.synthesisText,
    asset.group,
    asset.category,
    asset.src,
    asset.mimeType,
    asset.byteSize,
    asset.durationMs ?? "",
    asset.sha256,
    asset.voiceProfileVersion,
    asset.takeId,
  ].map(csvEscape).join(","));
  return `${header.join(",")}\n${rows.join("\n")}\n`;
}
