import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const projects = sqliteTable("projects", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description").notNull().default(""),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const imports = sqliteTable("imports", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  fileName: text("file_name").notNull(),
  format: text("format").notNull(),
  sourceHash: text("source_hash").notNull(),
  status: text("status").notNull(),
  totalRows: integer("total_rows").notNull(),
  insertedRows: integer("inserted_rows").notNull(),
  skippedRows: integer("skipped_rows").notNull(),
  errorRows: integer("error_rows").notNull(),
  summaryJson: text("summary_json").notNull(),
  createdAt: text("created_at").notNull(),
}, (table) => [index("imports_project_created_idx").on(table.projectId, table.createdAt)]);

export const phrases = sqliteTable("phrases", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  importId: text("import_id").references(() => imports.id, { onDelete: "set null" }),
  stableId: text("stable_id").notNull(),
  suppliedId: text("supplied_id"),
  sourceHash: text("source_hash").notNull(),
  sourceRow: integer("source_row").notNull(),
  displayText: text("display_text").notNull(),
  originalText: text("original_text").notNull(),
  synthesisText: text("synthesis_text"),
  normalizedText: text("normalized_text").notNull(),
  comparisonText: text("comparison_text").notNull(),
  groupCode: text("group_code").notNull().default("ungrouped"),
  category: text("category").notNull().default(""),
  tone: text("tone").notNull().default(""),
  englishMeaning: text("english_meaning").notNull().default(""),
  notes: text("notes").notNull().default(""),
  metadataJson: text("metadata_json").notNull().default("{}"),
  decision: text("decision").notNull().default("pending"),
  selectedTakeId: text("selected_take_id"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("phrases_project_stable_uidx").on(table.projectId, table.stableId),
  index("phrases_project_normalized_idx").on(table.projectId, table.normalizedText),
  index("phrases_project_decision_idx").on(table.projectId, table.decision),
  index("phrases_search_idx").on(table.projectId, table.displayText),
]);

export const phraseRevisions = sqliteTable("phrase_revisions", {
  id: text("id").primaryKey(),
  phraseId: text("phrase_id").notNull().references(() => phrases.id, { onDelete: "cascade" }),
  displayText: text("display_text").notNull(),
  synthesisText: text("synthesis_text"),
  groupCode: text("group_code").notNull(),
  category: text("category").notNull(),
  notes: text("notes").notNull(),
  reason: text("reason").notNull().default("edit"),
  createdAt: text("created_at").notNull(),
}, (table) => [index("phrase_revisions_phrase_created_idx").on(table.phraseId, table.createdAt)]);

export const voiceProfileVersions = sqliteTable("voice_profile_versions", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  label: text("label").notNull(),
  provider: text("provider").notNull().default("elevenlabs"),
  version: integer("version").notNull(),
  voiceId: text("voice_id").notNull(),
  voiceName: text("voice_name").notNull().default(""),
  modelId: text("model_id").notNull(),
  languageCode: text("language_code"),
  outputFormat: text("output_format").notNull(),
  stability: real("stability").notNull(),
  similarityBoost: real("similarity_boost").notNull(),
  style: real("style").notNull(),
  speed: real("speed").notNull(),
  useSpeakerBoost: integer("use_speaker_boost", { mode: "boolean" }).notNull(),
  notes: text("notes").notNull().default(""),
  lockedAt: text("locked_at"),
  isProduction: integer("is_production", { mode: "boolean" }).notNull().default(false),
  createdAt: text("created_at").notNull(),
}, (table) => [
  uniqueIndex("voice_profiles_project_version_uidx").on(table.projectId, table.version),
  index("voice_profiles_project_idx").on(table.projectId),
]);

export const ttsBatches = sqliteTable("tts_batches", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  voiceProfileVersionId: text("voice_profile_version_id").notNull().references(() => voiceProfileVersions.id),
  mode: text("mode").notNull(),
  status: text("status").notNull(),
  totalJobs: integer("total_jobs").notNull(),
  completedJobs: integer("completed_jobs").notNull().default(0),
  failedJobs: integer("failed_jobs").notNull().default(0),
  canceledJobs: integer("canceled_jobs").notNull().default(0),
  totalCharacters: integer("total_characters").notNull(),
  consecutiveFailures: integer("consecutive_failures").notNull().default(0),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
  completedAt: text("completed_at"),
}, (table) => [index("tts_batches_project_created_idx").on(table.projectId, table.createdAt)]);

export const ttsJobs = sqliteTable("tts_jobs", {
  id: text("id").primaryKey(),
  batchId: text("batch_id").notNull().references(() => ttsBatches.id, { onDelete: "cascade" }),
  projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  phraseId: text("phrase_id").notNull().references(() => phrases.id, { onDelete: "cascade" }),
  voiceProfileVersionId: text("voice_profile_version_id").notNull().references(() => voiceProfileVersions.id),
  provider: text("provider").notNull(),
  fingerprint: text("fingerprint").notNull(),
  status: text("status").notNull(),
  synthesisText: text("synthesis_text").notNull(),
  voiceId: text("voice_id").notNull(),
  modelId: text("model_id").notNull(),
  outputFormat: text("output_format").notNull(),
  languageCode: text("language_code"),
  settingsJson: text("settings_json").notNull(),
  seed: integer("seed").notNull(),
  attemptCount: integer("attempt_count").notNull().default(0),
  maxAttempts: integer("max_attempts").notNull().default(4),
  availableAt: text("available_at").notNull(),
  startedAt: text("started_at"),
  completedAt: text("completed_at"),
  providerRequestId: text("provider_request_id"),
  errorJson: text("error_json"),
  reusedTakeId: text("reused_take_id"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  index("tts_jobs_status_available_idx").on(table.status, table.availableAt),
  index("tts_jobs_fingerprint_idx").on(table.fingerprint, table.status),
  index("tts_jobs_batch_idx").on(table.batchId),
]);

export const audioTakes = sqliteTable("audio_takes", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  phraseId: text("phrase_id").notNull().references(() => phrases.id, { onDelete: "cascade" }),
  jobId: text("job_id").notNull().references(() => ttsJobs.id, { onDelete: "restrict" }),
  voiceProfileVersionId: text("voice_profile_version_id").notNull().references(() => voiceProfileVersions.id),
  provider: text("provider").notNull(),
  takeNumber: integer("take_number").notNull(),
  filePath: text("file_path").notNull(),
  mimeType: text("mime_type").notNull(),
  extension: text("extension").notNull(),
  byteSize: integer("byte_size").notNull(),
  durationMs: integer("duration_ms"),
  sha256: text("sha256").notNull(),
  source: text("source").notNull().default("tts"),
  reviewStatus: text("review_status").notNull().default("pending"),
  notes: text("notes").notNull().default(""),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("audio_takes_job_uidx").on(table.jobId),
  uniqueIndex("audio_takes_file_uidx").on(table.filePath),
  uniqueIndex("audio_takes_phrase_number_uidx").on(table.phraseId, table.takeNumber),
  index("audio_takes_phrase_review_idx").on(table.phraseId, table.reviewStatus),
]);

export const usageEvents = sqliteTable("usage_events", {
  id: text("id").primaryKey(),
  provider: text("provider").notNull(),
  operation: text("operation").notNull(),
  requestId: text("request_id"),
  estimatedUnits: integer("estimated_units"),
  actualUnits: integer("actual_units"),
  modelId: text("model_id"),
  jobId: text("job_id").references(() => ttsJobs.id, { onDelete: "set null" }),
  metadataJson: text("metadata_json").notNull().default("{}"),
  createdAt: text("created_at").notNull(),
}, (table) => [index("usage_events_provider_created_idx").on(table.provider, table.createdAt)]);

export const exportsTable = sqliteTable("exports", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  voiceProfileVersionId: text("voice_profile_version_id").notNull().references(() => voiceProfileVersions.id),
  label: text("label").notNull(),
  fingerprint: text("fingerprint").notNull(),
  status: text("status").notNull(),
  folderPath: text("folder_path").notNull(),
  zipPath: text("zip_path").notNull(),
  assetCount: integer("asset_count").notNull(),
  totalBytes: integer("total_bytes").notNull(),
  reportJson: text("report_json").notNull(),
  createdAt: text("created_at").notNull(),
}, (table) => [
  uniqueIndex("exports_project_fingerprint_uidx").on(table.projectId, table.fingerprint),
  index("exports_project_created_idx").on(table.projectId, table.createdAt),
]);

export const appSettings = sqliteTable("app_settings", {
  key: text("key").primaryKey(),
  valueJson: text("value_json").notNull(),
  updatedAt: text("updated_at").notNull(),
});
